packages:
  - packages/*

catalog:
  "typescript": "^5.9.2"
  "vite": "^7.1.7"
  "react": "^19.1.1"
  "react-dom": "^19.1.1"
  "@types/react": "^19.1.13"
  "@types/react-dom": "^19.1.9"
  "typedoc": "^0.28.13"
  "typedoc-plugin-markdown": "^4.9.0"
  "vite-plugin-dts": "^4.5.4"
  "vite-plugin-wasm": "^3.5.0"
  "vite-plugin-svgr": "^4.5.0"
  "@vitejs/plugin-react": "^5.0.3"
  "@biomejs/biome": "^2.2.4"
  "sharp": "^0.34.4"
  "framer-motion": "^12.23.18"
  "classnames": "^2.5.1"
  "@ungap/structured-clone": "^1.3.0"
