packages:
  - packages/*

catalog:
  "@biomejs/biome": ^2.3.10
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@ungap/structured-clone": ^1.3.0
  "@vitejs/plugin-react": ^5.1.2
  classnames: ^2.5.1
  framer-motion: ^12.23.26
  react: ^19.2.3
  react-dom: ^19.2.3
  sharp: ^0.34.5
  typedoc: ^0.28.15
  typedoc-plugin-markdown: ^4.9.0
  typescript: ^5.9.3
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-svgr: ^4.5.0
  vite-plugin-wasm: ^3.5.0
